general {
	lock_cmd = pidof hyprlock || hyprlock
	}

listener {
	timeout = 300
	on-timeout = bash -c '~/Scripts/hypridle-check.sh || exit 0; loginctl lock-session'
	on-resume = notify-send :"Resumed"
}

listener {
    timeout = 600
    on-timeout = bash -c '~/Scripts/hypridle-check.sh || exit 0; hyprctl dispatch dpms off' 
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

