# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = float, title:^(Calendar)$

$main = DP-1
$sec  = HDMI-A-1

workspace = 1, monitor:$main, default:true
workspace = 2, monitor:$main, gapsin:0, gapsout:0
workspace = 3, monitor:$main
workspace = 4, monitor:$main
workspace = 5, monitor:$main
workspace = 6, monitor:$main
workspace = 7, monitor:$sec, default:true
workspace = 8, monitor:$sec
workspace = 9, monitor:$sec
workspace = 10, monitor:$sec

# Common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Pick Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Volume Control)$
windowrule = float,title:^(Bluetooth Devices)$
windowrule = float,title:^(Library)$
windowrule = float,class:org.kde.gwenview

# Assign windows to workspaces
windowrule = workspace 6, title:OpenBoard
windowrule = float, title:OpenBoard

windowrule = workspace 5 silent, class:^(steam)$
windowrule = workspace 8, class:org.telegram.desktop
windowrule = workspace 8, class:discord
windowrule = workspace 9, class:(Spotify)

windowrule = float, class:xdg-desktop-portal-gtk
windowrule = size 1200 1000, class: xdg-desktop-portal-gtk

# Zoom 
windowrule = stayfocused, class:zoom, title:menu window
