[opener]

open = [
  { run = 'xdg-open "$@"', desc = "Open"}
]
nvim = [
  { run = 'nvim "$@"', desc = "Open file with nvim" },
]
fallback = [
  { run = 'micro "$@"', desc = "Open file with micro as fallback."},
]

#################
[open]
prepend_rules = [
  { name = "*.toml", use = "nvim"},
  { name = "*.tex", use = "nvim"},
]

append_rules = [
  { name = "*", use = "fallback" },
]

